apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "keycloak.fullname" . }}-realm
  labels:
    app: {{ template "keycloak.name" . }}
    chart: {{ template "keycloak.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
{{ (.Files.Glob "realms/*").AsConfig | indent 2 }}
